// Generated by CoffeeScript 1.6.3
(function() {
  var game, handleEvents;

  game = new Game;

  handleEvents = function() {
    var _this = this;
    window.onblur = function() {
      return game.stop();
    };
    window.onfocus = function() {
      return game.run();
    };
    return $(window).on('resize', function() {
      return game.resize();
    });
  };

  handleEvents();

  game.run();

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
